INSERT INTO APPLICATION(APPLICATION_STATE) VALUES('NEW');
INSERT INTO APPLICANT(APPLICATION_ID, APPLICANT_ORDER, FIRST_NAME, LAST_NAME) VALUES((SELECT MAX(APPLICATION_ID) FROM APPLICATION), 1, 'FNAME', 'LNAME');
INSERT INTO ADDRESS(APPLICANT_ID, ADDRESS_TYPE, STREET_NUMBER, STREET_NAME, STREET_TYPE) VALUES ((SELECT MAX(APPLICANT_ID) FROM APPLICANT), 'RESIDENTIAL', '1', 'Oxford', 'ST');
INSERT INTO CONTACT_DETAILS(APPLICANT_ID, EMAIL_ADDRESS) VALUES ((SELECT MAX(APPLICANT_ID) FROM APPLICANT), 'a@b.com');
INSERT INTO PHONE_NUMBER(APPLICANT_ID, PHONE_TYPE, COUNTRY_CODE, AREA_CODE, NUMBER, EXTENSION) VALUES ((SELECT MAX(APPLICANT_ID) FROM APPLICANT), 'HOME', '44', '7', '123456789', 'extension');