-- SELECT * FROM PUBLIC.APPLICATION;

CREATE TABLE PUBLIC.APPLICATION(
  APPLICATION_ID INTEGER IDENTITY PRIMARY KEY,
  APPLICATION_STATE VARCHAR(255)
);

CREATE TABLE PUBLIC.APPLICANT(
  APPLICANT_ID INTEGER IDENTITY PRIMARY KEY,
  APPLICATION_ID INTEGER NOT NULL,
  APPLICANT_ORDER INTEGER NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255) NOT NULL
);

ALTER TABLE PUBLIC.APPLICANT
  ADD FOREIGN KEY (APPLICATION_ID)
  REFERENCES PUBLIC.APPLICATION(APPLICATION_ID);

CREATE TABLE PUBLIC.ADDRESS(
  ADDRESS_ID INTEGER IDENTITY PRIMARY KEY,
  APPLICANT_ID INTEGER,
  ADDRESS_TYPE VARCHAR(255),
  STREET_NUMBER VARCHAR(255),
  STREET_NAME VARCHAR(255),
  STREET_TYPE VARCHAR(255)
);

ALTER TABLE PUBLIC.ADDRESS
  ADD FOREIGN KEY (APPLICANT_ID)
  REFERENCES PUBLIC.APPLICANT(APPLICANT_ID);

CREATE UNIQUE INDEX PUBLIC.adr_primary
  ON PUBLIC.ADDRESS (APPLICANT_ID, ADDRESS_TYPE);

CREATE TABLE PUBLIC.CONTACT_DETAILS(
  APPLICANT_ID INTEGER PRIMARY KEY,
  EMAIL_ADDRESS VARCHAR(255)
);

ALTER TABLE PUBLIC.CONTACT_DETAILS
  ADD FOREIGN KEY (APPLICANT_ID)
  REFERENCES PUBLIC.APPLICANT(APPLICANT_ID);

CREATE TABLE PUBLIC.PHONE_NUMBER(
  APPLICANT_ID INTEGER PRIMARY KEY,
  PHONE_TYPE VARCHAR(255),
  COUNTRY_CODE VARCHAR(255),
  AREA_CODE VARCHAR(255),
  NUMBER VARCHAR(255),
  EXTENSION VARCHAR(255),
);

ALTER TABLE PUBLIC.PHONE_NUMBER
  ADD FOREIGN KEY (APPLICANT_ID)
  REFERENCES PUBLIC.APPLICANT(APPLICANT_ID);

CREATE UNIQUE INDEX PUBLIC.phn_primary
  ON PUBLIC.PHONE_NUMBER (APPLICANT_ID, PHONE_TYPE);